Started processing ACM0 month data, from  2024-12-18 to 2025-01-17 on 2025-01-18 at 05:30:01
Traceback (most recent call last):
  File "/home/pi/UKRAA_muons/scripts/ProcessDataMonthACM0.py", line 92, in <module>
    with open(f,'rb') as fd:
         ^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/UKRAA_muons/data/processed/day/ACM0/2024/2024-12/2024-12-18.txt'
Started processing ACM0 month data, from  2024-12-19 to 2025-01-18 on 2025-01-19 at 05:30:01
Traceback (most recent call last):
  File "/home/pi/UKRAA_muons/scripts/ProcessDataMonthACM0.py", line 92, in <module>
    with open(f,'rb') as fd:
         ^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/UKRAA_muons/data/processed/day/ACM0/2024/2024-12/2024-12-19.txt'
Started processing ACM0 month data, from  2024-12-20 to 2025-01-19 on 2025-01-20 at 05:30:01
Traceback (most recent call last):
  File "/home/pi/UKRAA_muons/scripts/ProcessDataMonthACM0.py", line 92, in <module>
    with open(f,'rb') as fd:
         ^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/UKRAA_muons/data/processed/day/ACM0/2024/2024-12/2024-12-20.txt'
